name: yt_migrate
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Ryan Gonzalez <rymg19@gmail.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  archive: ^2.0.0
  args: ^1.6.0
  cli_util: ^0.1.3
  googleapis: ^0.54.0
  googleapis_auth: ^0.2.11
  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0

executables:
  yt-migrate: main
